steps:
  # install dependencies
  - name: python:3.9-slim
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
  
  - name: python:3.9-slim
    entrypoint: pip
    args: ["install", "-r", "requirements-test.txt", "--user"]

  # run in python 3.9 which is latest version in Cloud Composer
  - name: python:3.9-slim
    entrypoint: python3.9
    args: ["-m", "pytest", "-s", "dags/"]
